version: "3.8"
services:
    server:
        build: server
        restart: always
        ports:
            -   '5000:5000'
        volumes:
            -   ./server/src:/code
            -   ./server/db:/db
        networks:
            -   default-network

    client:
        build: demo/client
#        restart: always
        volumes:
            -   ./server/src:/code
        networks:
            -   default-network
        depends_on:
            -   'server'

    adversary:
        build: demo/adversary
        volumes:
            -   ./server/src:/code
        networks:
            -   default-network
        depends_on:
            -   client

networks:
    default-network: